### ISSUE TITLE
Data Grid View goes nuts after selecting build number from the list

### ISSUE THREAD

**Issue by Suleman-Elahi** [PeterStrick/ViVeTool-GUI#11]
**Describe the bug**

After selecting a build from the list, the data grid view is flickering a lot, making it hard to select a feature to enable. Other components of the GUI are irresponsive too.

**To Reproduce**
1. Extract the ZIP.
2. Launch ViVeTool_GUI.exe
3. Select a build number from the dropdown

**Expected behavior**

 Should be able to reliably select the feature to enable.

**Screenshots**

https://user-images.githubusercontent.com/24384996/161738887-e1ad463c-7e60-44a1-9a6d-0835c536e5e4.mp4

**Desktop (please complete the following information):**
 - Windows Build: 22581.200
 - ViVeTool-GUI Version: 1.6

**Comment by PeterStrick** [comment]
I don't think I can do much about the flickering/unresponsiveness. Only thing I can do is make the Application a bit Flicker or completely unresponsive.

**Comment by Suleman-Elahi** [comment]
Why do you think it keep scrolling. I think it's a major issue. It prevents user from selecting a feature from the list.

**Comment by PeterStrick** [comment]
> Why do you think it keep scrolling. I think it's a major issue. It prevents user from selecting a feature from the list.

Well ViVeTool GUI loads each feature Line by Line in the background, you'll have to wait anyways for it to load in. I could probably make it so that it doesn't Select or Scroll anything while loading the Features in.

**Comment by PeterStrick** [comment]
The flickering should be somewhat gone with Version 1.6.1. The GUI Flickering depends on the hosts GPU.

The GUI is unresponsive when loading a Build, because the UI Thread can only draw one thing at a time.

If you have found other Bugs or have Feature Requests, feel free to open a new Issue.
