### ISSUE TITLE
Tabs Explorer Windows 11 Insider 22593.1

### ISSUE THREAD

**Issue by ryanvanwin** [PeterStrick/ViVeTool-GUI#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanvanwin** [comment]
Please add tabs file explorer to windows 11 insider build 22593.1

**Comment by fragtion** [comment]
Why did you close the issue? I'm here for the same reason

**Comment by PeterStrick** [comment]
> Please add tabs file explorer to windows 11 insider build 22593.1

I can´t influence the Feature IDs that ViVeTool GUI uses.
