### ISSUE TITLE
22000 not supported

### ISSUE THREAD

**Issue by Ganesha2282882** [PeterStrick/ViVeTool-GUI#15]
**Is your feature request related to a problem? Please describe.**

I'm frustrated because there is no list for 22000.675. I don't want to use the Insider Program because I am on a multi-user system (I am an Admin) and it will spam toast notifications on other users.

**Describe the solution you'd like**
Add 22000 as an option

**Describe alternatives you've considered**
Use 22449's list

**Additional context**
![image](https://user-images.githubusercontent.com/59745725/171717594-598558ca-0b79-4e9d-8682-c84432f3e017.png)
![image](https://user-images.githubusercontent.com/59745725/171717661-4574b9c0-d0f6-4a9e-82e2-86904969794f.png)

**Comment by PeterStrick** [comment]
This issue has been addressed and fixed in Version 1.6.2.0
You can use a portable Version of 1.6.2.0 here, as I am preparing for Version 1.7

[ViVeTool GUI - Version 1.6.2.0.zip](https://github.com/PeterStrick/ViVeTool-GUI/files/8834369/ViVeTool.GUI.-.Version.1.6.2.0.zip)

**Comment by Ganesha2282882** [comment]
Thanks!
