### ISSUE TITLE
Add GUI multilanguage

### ISSUE THREAD

**Issue by bovirus** [PeterStrick/ViVeTool-GUI#16]
**Is your feature request related to a problem? Please describe.**
No. Is an additional feature

**Describe the solution you'd like**
Could you pelase modify teh source to have a multilanguage GUI

**Describe alternatives you've considered**

**Additional context**

**Comment by PeterStrick** [comment]
I am working on it for version 1.7.
It just takes some time and research, on the best way to accomplish this.

**Comment by TheDemianGaming** [comment]
> I am working on it for version 1.7.
> It just takes some time and research, on the best way to accomplish this.

Hello.  I downloaded your Vivetool GUI program, I have a question, where do I get the function IDs from?  I understand from the Windows SDK?  If yes, how can I find them?  I currently have Windows 11 build 22621.160 installed, and I need a feature ID for explorer tabs, but for some reason your program does not have this build.  Can you tell me where you can find the function identifiers, or at least write the identifier for the tabs

**Comment by PeterStrick** [comment]
> > I am working on it for version 1.7.
> > It just takes some time and research, on the best way to accomplish this.
> 
> Hello. I downloaded your Vivetool GUI program, I have a question, where do I get the function IDs from? I understand from the Windows SDK? If yes, how can I find them? I currently have Windows 11 build 22621.160 installed, and I need a feature ID for explorer tabs, but for some reason your program does not have this build. Can you tell me where you can find the function identifiers, or at least write the identifier for the tabs

The Windows 11 Tabs feature is only in the Dev Build 25136.
Its ID is 37634385

**Comment by PeterStrick** [comment]
> > > > I am working on it for version 1.7.
> > > > It just takes some time and research, on the best way to accomplish this.
> > > 
> > > 
> > > Hello. I downloaded your Vivetool GUI program, I have a question, where do I get the function IDs from? I understand from the Windows SDK? If yes, how can I find them? I currently have Windows 11 build 22621.160 installed, and I need a feature ID for explorer tabs, but for some reason your program does not have this build. Can you tell me where you can find the function identifiers, or at least write the identifier for the tabs
> > 
> > 
> > The Windows 11 Tabs feature is only in the Dev Build 25136.
> > Its ID is 37634385
> 
> Thanks for answering. I have another question, under build 22621.160 are there any functions activated through your program?

There doesn´t seem to be a Feature List available for Build 22621. Only for Build 22616 and 25115+

Windows 11 Beta/Release Preview Builds usually do not get a Feature List on release in the [mach2 repo](https://github.com/riverar/mach2/tree/master/features).

Also next time please create a new issue @TheDemianGaming

**Comment by FinaFina233** [comment]
> > > > I am working on it for version 1.7.
> > > > It just takes some time and research, on the best way to accomplish this.
> > > 
> > > 
> > > Hello. I downloaded your Vivetool GUI program, I have a question, where do I get the function IDs from? I understand from the Windows SDK? If yes, how can I find them? I currently have Windows 11 build 22621.160 installed, and I need a feature ID for explorer tabs, but for some reason your program does not have this build. Can you tell me where you can find the function identifiers, or at least write the identifier for the tabs
> > 
> > 
> > The Windows 11 Tabs feature is only in the Dev Build 25136.
> > Its ID is 37634385
> 
> Thanks for answering. I have another question, under build 22621.160 are there any functions activated through your program?

you can enable file explorer tabs by enable the following features for 22621.160
39145991
37634385
36354489

**Comment by TheDemianGaming** [comment]
> > > > > I am working on it for version 1.7.
> > > > > It just takes some time and research, on the best way to accomplish this.
> > > > 
> > > > 
> > > > Hello. I downloaded your Vivetool GUI program, I have a question, where do I get the function IDs from? I understand from the Windows SDK? If yes, how can I find them? I currently have Windows 11 build 22621.160 installed, and I need a feature ID for explorer tabs, but for some reason your program does not have this build. Can you tell me where you can find the function identifiers, or at least write the identifier for the tabs
> > > 
> > > 
> > > The Windows 11 Tabs feature is only in the Dev Build 25136.
> > > Its ID is 37634385
> > 
> > 
> > Thanks for answering. I have another question, under build 22621.160 are there any functions activated through your program?
> 
> you can enable file explorer tabs by enable the following features for 22621.160 39145991 37634385 36354489

Thank you

**Comment by PeterStrick** [comment]
For now implemented in the Emergency Bugfix Release 1.6.999.3, either automatically depending on your System Locale, or as a Drop Down under Settings

A way to help translate Strings and Text for ViVeTool GUI can be accomplished by using the Hosted Weblate instance at https://weblate.rawrr.dev

Current Language Implementations as of right now: **English, German, Chinese (SImplified), Indonesian, Italian, Japanese, Polish**

Some Languages may be more complete in their translation than others.

Will be properly bug tested and finished until Version 1.7 releases to the public.

**Comment by bovirus** [comment]
@PeterStrick 

Coudl you please enable me (user = roberto . boriotti at gmail . com) to revise the translation on Weblate? Thanks.

**Comment by PeterStrick** [comment]
> @PeterStrick
> 
> Coudl you please enable me (user = roberto . boriotti at gmail . com) to revise the translation on Weblate? Thanks.

You should be able to suggest a Translation without a Weblate Account, unless I messed up something on the configuration side

**Comment by PeterStrick** [comment]
Ah Sorry, Google and GitHub Logins were broken since they still pointed to the old defunct domain. I now fixed both of them

**Comment by bovirus** [comment]
@PeterStrick

My idea is as I'm doing for Weblate project or Loseless project on Weblate to enable me to edit directly the strings.
I'm working for many sofwtare projct as official translator (Inno Setup, NSIS, Weblate, Filezilla, etc).

**Comment by PeterStrick** [comment]
> @PeterStrick
> 
> My idea is as I'm doing for Weblate project or Loseless project on Weblate to enable me to edit directly the strings. I'm working for many sofwtare projct as official translator (Inno Setup, NSIS, Weblate, Filezilla, etc).

Well if you tell me how to do that than sure, already plagued myself trying to setup RegEX for component discovery for a fair bit

**Comment by bovirus** [comment]
@PeterStrick

Enable me to access and revise strings in 

https://weblate.rawrr.dev/projects/vivetool-gui/

Probably you should enable in your Weblate contrl panel my user (roberto . boriotti at gmail . com) to revise directly the strings.

**Comment by PeterStrick** [comment]
> @PeterStrick
> 
> Hi.
> 
> I regsitered my account in https://weblate.rawrr.dev/ and now I'm able tor evise strings.

You should also be able to edit Source Strings now and more

**Comment by bovirus** [comment]
@PeterStrick 

Italian tranlation completed (100%).
Please add italian language in next build.

**Comment by bovirus** [comment]
@PeterStrick 

How can get the file for italian GUI to test it in place?

**Comment by PeterStrick** [comment]
> @PeterStrick
> 
> How can get the file for italian GUI to test it in place?

I have setup a GitHub action that automatically compiles and uploads a ViVeTool GUI Build on each commit

The ZIP File can be downloaded from the latest GitHub Action under `Artifacts`

A link of an Artifact that recently uploaded is https://github.com/PeterStrick/ViVeTool-GUI/suites/14348064902/artifacts/807835586

**Comment by bovirus** [comment]
@PeterStrick 

Thanks.

Is there a link to access to the list of latest compilation (artifacts)?

**Comment by PeterStrick** [comment]
> @PeterStrick
> 
> Thanks.
> 
> Is there a link to access to the list of latest compilation (artifacts)?

Artifacts can be downloaded corresponding to each Github Action on the [Actions Tab in GitHub](https://github.com/PeterStrick/ViVeTool-GUI/actions)
