### ISSUE TITLE
Windows 11 Build 25131 - File Explorer tabs

### ISSUE THREAD

**Issue by ALIENQuake** [PeterStrick/ViVeTool-GUI#18]
Hi,

I'm not sure if this app can do it but it's possible to enable the "File Explorer tabs" feature? I've tried searching 'explorer' and 'tab' but nothing came out. If it's out of the scope then no problem.

**Comment by PeterStrick** [comment]
> Hi,
> 
> I'm not sure if this app can do it but it's possible to enable the "File Explorer tabs" feature? I've tried searching 'explorer' and 'tab' but nothing came out. If it's out of the scope then no problem.

Hi, here are some ViVeTool IDs for Build 25136:
- File Explorer Tabs: 37634385
- New File Explorer Navigation Panel: 36354489
- Microsoft Edge Desktop Search: 37969115
- Search Box Lower Left: 37010913

Just search the IDs or manually enable them by pressing F12
