### ISSUE TITLE
Common Feature IDs

### ISSUE THREAD

**Issue by PeterStrick** [PeterStrick/ViVeTool-GUI#19]
Commonly asked for ViVeTool IDs, gathered from Media and News sources sorted per Build.

<details>
  <summary>ViVeTool IDs for Build 25136</summary>

Feature | Name | ID
--- | --- | ---
File Explorer Tabs | TIFE | 37634385
New File Explorer Navigation Panel | SV2Navpane | 36354489
Microsoft Edge Desktop Search | DesktopSearchBox | 37969115
Search Box Lower Left | SearchBoxLowerLeft | 37010913
  
</details>

**Comment by maicol07** [comment]
I'll add to this list the new fluent design Apppicker (build 25174):

|          Feature         |    Name   |    ID    |
|:------------------------:|:---------:|:--------:|
| Fluent design App picker | Apppicker | 36302090 |

**Comment by Dhyfer1** [comment]
To activate the new taskbar overflow in Windows 11 22H2 Beta, you need these ID's: 35620394 and 35620394
Source: https://www.neowin.net/news/how-to-enable-new-taskbar-overflow-in-windows-11-22h2-beta/

**Comment by Dhyfer1** [comment]
To activate the Updated tray area in Windows 11 25193 (A/B testing) with redesigned buttons and tooltips, this ID is required: 26008830. Source: [Reddit](https://www.reddit.com/r/Windows11/comments/x3zfem/updated_tray_area_in_windows_11_25193_ab_testing/?utm_source=share&utm_medium=web2x&context=3)

**Comment by kid1485** [comment]
To activate the New Game Pass Widget in Windows 11 Build 25201 Insider Preview Build for the Dev Channel, this ID is required: id:36094217
Source: https://itstechbased.com/how-to-enable-new-game-pass-widget-in-windows-11-25201/

**Comment by Dhyfer1** [comment]
To enable the new Task Manager search in Windows 11 build 25231, this ID is required: 39420424
Source: https://www.neowin.net/news/you-can-now-enable-a-hidden-task-manager-search-feature-inside-windows-11/

**Comment by ericgl** [comment]
Anyone knows which ViveTool ID (or better yet - exact reg key) enables the new formatting options in Windows Notepad?
I have the latest version of Notepad installed **11.2504.52.0** (as of 2025-05-30), yet the formatting controls are not showing up in the toolbar. I have no idea which reg key under HKLM\SYSTEM\CurrentControlSet\Control\FeatureManagement\Overrides\ enables them.
