### ISSUE TITLE
Why is there no 22621?

### ISSUE THREAD

**Issue by hedhehd** [PeterStrick/ViVeTool-GUI#20]
**Describe the bug**
So the issue is that I need to activate the new navigation panel and tabs but it doesn't include this build.

**To Reproduce**
1. Click the arrow next to where your build number is

**Expected behavior**
That it pops up the build (22621) that I wanted.

**Screenshots**
![image](https://user-images.githubusercontent.com/81228260/173441781-4807586e-252e-4b43-956e-db843f1c096e.png)

**Desktop (please complete the following information):**
 - Windows Build: 22621
 - ViVeTool-GUI Version: 1.6.2.0

**Comment by hedhehd** [comment]
I don't know if this is a suggestion or a bug but this is very important.

**Comment by PeterStrick** [comment]
A Feature List for Build 22621 [currently doesn´t exist](https://github.com/riverar/mach2/tree/master/features) and there isn´t much that I can do about it. You can create one yourself using the ViVeTool GUI - Feature Scanner.

**Comment by PeterStrick** [comment]
Also, the new navigation Panel and Tabs are **only** available for the **Dev** Channel. Not the Beta channel.

**Comment by KaidudePlays** [comment]
@PeterStrick The latest beta build (22621.160) just added them.  Take a look for yourself here: [Blog post](https://blogs.windows.com/windows-insider/2022/06/13/announcing-windows-11-insider-preview-build-22621-160/)

**Comment by PeterStrick** [comment]
> @PeterStrick The latest beta build (22621.160) just added them. Take a look for yourself here: [Blog post](https://blogs.windows.com/windows-insider/2022/06/13/announcing-windows-11-insider-preview-build-22621-160/)

Sorry, missed that one. Currently have no IDs for the Beta Build at hand, and no Feature List either.

**Comment by PeterStrick** [comment]
> > @PeterStrick The latest beta build (22621.160) just added them. Take a look for yourself here: [Blog post](https://blogs.windows.com/windows-insider/2022/06/13/announcing-windows-11-insider-preview-build-22621-160/)
> 
> Sorry, missed that one. Currently have no IDs for the Beta Build at hand, and no Feature List either.

IDs have been found and cataloged in #19
