### ISSUE TITLE
Add User comments feature

### ISSUE THREAD

**Issue by lauraloldk** [PeterStrick/ViVeTool-GUI#23]
please make a button, that allows users to comment the feature id, like "what does the id unlocks/enable" and "Where to find the new feature,s" and a file upload to add Screenshots, regedit files or scripts to fix things related to the id. all the comments will then be added to the database, and moderators have the option to edit/remove the comments or the files related to it. this will make it more easy for the users to understand what they enables/disables

**Comment by PeterStrick** [comment]
I could add user comments as a new column to ViVeTool GUI. Adding or uploading files/screenshots won´t properly be added as I don´t have space to host them.

I´ll see what I can do

**Comment by lauraloldk** [comment]
Also add a checkbox "Only show commented Feature id,s for this build" to the app

**Comment by PeterStrick** [comment]
> Also add a checkbox "Only show commented Feature id,s for this build" to the app

I'm currently looking at a way to add a column for the Comments, which will be sortable.

The System/API for the comments has already been implemented and tested.

**Comment by PeterStrick** [comment]
WIll be available in Version 1.7
