### ISSUE TITLE
I am trying to enable the new task manager but it is not working

### ISSUE THREAD

**Issue by WoolenDoolen** [PeterStrick/ViVeTool-GUI#27]
**Describe the bug**
I am on windows 11, I have enabled all 3 of the "taskmanager" options on the gui and when i restart everything nothing changes, the task manager is still the windows 10 one.
![image](https://user-images.githubusercontent.com/84048395/180628351-3d1c0b32-c1d9-4b0d-8ed6-981aa53f0bc9.png)

 - Windows Build: Windows 11 Home OS build 22000.795
 - ViVeTool-GUI Version: 1.6.2

**Comment by PeterStrick** [comment]
You have selected Build **25158** in ViVeTool GUI but you are running Windows 11 Build **22000.795**

Currently looking at the Feature List for Build 22000 there are 5 Task Manager Options

-   TaskManagerEndTaskSnapOneTrace: 19453616
-   TaskManagerExperiment: 8749962
-   TaskManagerFeatureExperiment: 15681380
-   TaskManagerHealthTelemetry: 18631046
-   TaskManagerSetDefaultStartupTab: 19349505

You might want to try and enable them and reboot to see if that works

**Comment by WoolenDoolen** [comment]
i have done that and nothing has changed, rebooted and everything.

![image](https://user-images.githubusercontent.com/84048395/180688750-dc52b905-6aa7-4e25-885e-a6a2390a68a5.png)

**Comment by WoolenDoolen** [comment]
> i have done that and nothing has changed, rebooted and everything.
> 
> ![image](https://user-images.githubusercontent.com/84048395/180688750-dc52b905-6aa7-4e25-885e-a6a2390a68a5.png)

to be clkear, what im looking for is the new windows 11 dark theme task manager that looks like this, 
![image](https://user-images.githubusercontent.com/84048395/180914049-412f0711-9bd8-42ae-8120-d9c9b02189ed.png)

**Comment by PeterStrick** [comment]
Oh, the new Task Manager is only available for **Dev and Beta** Windows 11 Insiders.

It is not available for normal Windows 11 Build 22000 and neither ViVeTool or ViVeTool GUI can change that.
