### ISSUE TITLE
Add other id in vivetool gui

### ISSUE THREAD

**Issue by kid1485** [PeterStrick/ViVeTool-GUI#28]
**Is your feature request related to a problem? Please describe.**
I do not find id 34300186 named WidgetsExpandedView to enable expanded view widget in window 11 Build 25201 Insider Preview Build for Dev Channel,but if i use vivetool , i can find and enable it

**Describe the solution you'd like**
I want you to add file contain list of these feature's id similar with extra dictionary file in github vive

**Comment by PeterStrick** [comment]
It is weird that this ID doesn't show up in the Mach2 list, for now, you can find common IDs under #19 

Maybe I'll add a Feature to ViVeTool GUI 1.7 that lists all Community/Common IDs in conjunction with the Comment Feature
