### ISSUE TITLE
Add variant & fixpriority flag

### ISSUE THREAD

**Issue by jovanzers** [PeterStrick/ViVeTool-GUI#35]
Is it possible to add this feature?

Variant example enable search bar with variant 3:
`vivetool /enable /id:39263329 /variant:3`

Fixpriority example (https://github.com/thebookisclosed/ViVe/releases/tag/v0.3.2):
`vivetool /fixpriority`

**Comment by PeterStrick** [comment]
The Variant Feature and "/fixpriority" Function need an upgrade from the ViVeTool API that the GUI uses.

The Variant Feature could be included in the "Manually change a Feature" Dialog

The Fixpriority Function could be executed before the GUI closes

**Comment by PeterStrick** [comment]
For now, I'm working on the Comments Feature and Language Localization in the [1.7 Branch](https://github.com/PeterStrick/ViVeTool-GUI/tree/v1.7-Testing)

Upgrading the API will come after that

**Comment by jovanzers** [comment]
Thank you, please take a look #36 I added Indonesian translation

**Comment by PeterStrick** [comment]
For now fixed in the Emergency Bugfix Release 1.6.999.3, under the "Manually change a Feature" Option

A Fix Priorities Button is under the same Option mentioned above

Will be properly bug tested until Version 1.7 releases to the public.
