### ISSUE TITLE
[Bug] I waited 9 hours for Feature Scanner to complete its search, but it didn't save anything.....

### ISSUE THREAD

**Issue by AndreyRGW** [PeterStrick/ViVeTool-GUI#38]

**Comment by PeterStrick** [comment]
The current Feature Scanner should have a Button at the end of the Page to save the Results to your Desktop.

The Results file should also be named as the Build you were using it on under the Debug Symbols Folder that you have selected in the Initial Step

<br>

The Feature Scanner is gonna get a revamp in Version 1.7 for the entire "Saving the Results File" aspect by asking you where to save it, which will/should also reduce Write Access Problems like #37 

---

Also Sorry for the delayed Response, was dealing with Family Issues and School Exams so didn't really have time at all to work on ViVeTool GUI, luckily my Exams are all finished, Family Issues kinda over and my Winter Holiday for School and Work is gonna start from 22th December to New Years Eve which means plenty of more time to work on ViVeTool GUI

**Comment by PeterStrick** [comment]
For now implemented in the Emergency Bugfix Release 1.6.999.3

Will be properly bug tested until Version 1.7 releases to the public.
