### ISSUE TITLE
Possible vivetool gui improvements: feature variants

### ISSUE THREAD

**Issue by KaidudePlays** [PeterStrick/ViVeTool-GUI#39]
**Is your feature request related to a problem? Please describe.**
This is related to a function added in the new vivetool command line interface version release.  Simply, now the command format is "vivetool /enable /id:[ID number] /variant:# ", and that added in a new function to enable variants of different features like the new search bar. 

**Describe the solution you'd like**
As shown above, I would like to see some sort of way to enable feature variants implemented like the vivetool 0.3 release [link to release](https://github.com/thebookisclosed/ViVe/releases/tag/v0.3.0)

**Describe alternatives you've considered**
There really are no alternatives that I can think of other than using the new command syntax in the command link version.  

**Additional context**
As one example of why this would be useful:  here is a few search bars from a past dev build that require that variant tag to enable that specific one: (command for reference: vivetool /enable /id:39072097 /variant:[1-5])
![image](https://user-images.githubusercontent.com/105994236/205203706-ec64209f-01dd-438e-a9f6-dc87702fcc7c.png)

**Comment by KaidudePlays** [comment]
Edit: as found in build [25158](https://blogs.windows.com/windows-insider/2022/07/13/announcing-windows-11-insider-preview-build-25158/), the 5 search bar variants that were being tested at the time needed that new vivetool release to forcefully enable the variants

**Comment by PeterStrick** [comment]
The new Varients feature of ViveTool 0.3+ requires an update to Version 0.3 of the ViVe API that ViVeTool GUI currently uses.

This is planned, along with more in the 1.7 Release

**Comment by PeterStrick** [comment]
Support for Feature Variants has been introduced into the v1.7-Testing branch, alongside the latest ViVe API

I just currently don't have a Windows Insider ISO at hand to test it, that has a Feature Variant Option even available

**Comment by PeterStrick** [comment]
For now implemented in the Emergency Bugfix Release 1.6.999.3, under the "Manually change a Feature" Option

Will be properly bug tested until Version 1.7 releases to the public.
