### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ANON-IN** [PeterStrick/ViVeTool-GUI#4]
Windows Build: 19044.1586
ViVeTool-GUI Version: 1.5.1 Portable

![error](https://user-images.githubusercontent.com/78699861/157674068-c9e7cb98-8aba-4052-ac95-c6ddc4558f6b.png)

**Comment by PeterStrick** [comment]
Huh this seems weird. Let me try to reproduce this

**Comment by PeterStrick** [comment]
I was unable to reproduce this on the exact Build you have installed, nor on the Windows 11 Build 22572. Do you maybe have Antivirus/Optimization Software installed that could intervene with ViVeTool-GUI?

**Comment by PeterStrick** [comment]
Well then, if you still experience Issues with ViVeTool-GUI, comment here or open a new issue.

**Comment by Forensic-Cyber** [comment]
I dont have any AV running om this machine even Windows defender is removed using st1ckys powershell script.
none of your GUI build work on this OS. any update ?

**Comment by PeterStrick** [comment]
> I dont have any AV running on this machine even Windows defender is removed. none of your GUI build work on this OS. Why you closed my issue without any response from me ? seems weird.

I just tested version 1.5.1 Portable on your exact Build without issues or crashes. Could you maybe open `%LOCALAPPDATA%\CrashDumps` in a new File Explorer Window and see if ViVeTool-GUI created a crash dump? If yes it would be helpful if you uploaded it here for me to look into

**Comment by ANON-IN** [comment]
![error](https://user-images.githubusercontent.com/78699861/157909275-0f1cdf01-add8-4345-94a2-b8a6daaf1243.png)
No crash dump.

**Comment by PeterStrick** [comment]
Well, I am out of ideas sorry. ViVeTool and ViVeTool-GUI is usually used in combination with a Windows Insider Dev/Beta Build, not a normal Windows 10 Build

**Comment by ANON-IN** [comment]
Resolved as i was executing it on offline virtual machine & when i tried it on internet connected Host OS it works perfectly without error.
Its My fault not yours.

**Comment by PeterStrick** [comment]
> Resolved as i was executing it on offline virtual machine & when i tried it on internet connected Host OS it works perfectly without error. Its My fault not yours.

Well, actually it is supposed to throw an error message and not outright crash. Weird

**Comment by PeterStrick** [comment]
@ANON-IN You can now update to 1.5.2. It was crashing because in order to populate the Combo Box, it needs to contact the GitHub API. No Internet no GitHub API
##### (Why didn´t I think of putting Network Checks in an almost Online Only Application)

**Comment by ANON-IN** [comment]
> @ANON-IN You can now update to 1.5.2. It was crashing because in order to populate the Combo Box, it needs to contact the GitHub API. No Internet no GitHub API
> ##### (Why didn´t I think of putting Network Checks in an almost Online Only Application)

Awesome now it seems perfect as user will see a Pop up to provide internet access or else use F12 key to do anything manualy 👍🏻 
Now dot net application is not crashing when we click close on pop up .
why not create the application with dot net core 6 runtime support that will be more then awesome 🥇

**Comment by PeterStrick** [comment]
> why not create the application with dot net core 6 runtime support that will be more then awesome 🥇

Well, I simply use .Net Framework 4.8 as it is per default pre-installed on all Windows 10/11 Devices. I could use .Net 6 but then either the ZIP File Size increases or the user has to install .Net 6 themselves.
