### ISSUE TITLE
[Bug] ViVeTool-GUl is unable to populate the Build ComboBox, if the Device isn't connected to the lnternet, orif the GitHub APl is unreachable. 

### ISSUE THREAD

**Issue by jzhang1018** [PeterStrick/ViVeTool-GUI#41]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Build: 
 - ViVeTool-GUI Version:

**Comment by jzhang1018** [comment]
how can solve this problem？

**Comment by PeterStrick** [comment]
This Issue either occurs if the Github API is unreachable or if your device isn't connected to the Internet.

**Comment by PeterStrick** [comment]
Closed due to inactivity and not really a ViVeTool GUI problem, but more over a Internet/GitHub one
