### ISSUE TITLE
Suggestion: order builds in decreasing order

### ISSUE THREAD

**Issue by maicol07** [PeterStrick/ViVeTool-GUI#5]
**Is your feature request related to a problem? Please describe.**
When I want to use ViveTool GUI I have to select my build at the end of the list

**Describe the solution you'd like**
Builds are ordered in decreasing order

**Comment by PeterStrick** [comment]
This is an easy change, I´ll add it to the Version 1.6 Project as I also want to investigate other issues and features.

**Comment by PeterStrick** [comment]
The Change as of now is live on the [Version-1.6](https://github.com/PeterStrick/ViVeTool-GUI/tree/Version-1.6) Branch
