### ISSUE TITLE
Automatically detect build when starting and load all the flags

### ISSUE THREAD

**Issue by maicol07** [PeterStrick/ViVeTool-GUI#6]
**Is your feature request related to a problem? Please describe.**
When I want to use ViveTool GUI I have to select my build at the end of the list

**Describe the solution you'd like**
Detect automatically current build and load all the possible flags.  Maybe this behaviour can be toggled with a checkbox

**Comment by PeterStrick** [comment]
The Change as of now is live on the [Version-1.6](https://github.com/PeterStrick/ViVeTool-GUI/tree/Version-1.6) Branch

**Comment by PeterStrick** [comment]
You can now try out #5 and #6 by using [Pre-Release 1 of Version 1.6](https://github.com/PeterStrick/ViVeTool-GUI/releases/tag/v1.6-prerelease1). I´ll close both of your issues now. If new ones appear make sure to notify me!

**Comment by maicol07** [comment]
@PeterStrick actually, this doesn't work very well: the setting selects the latest build (which is the Canary one, with the highest build number), but not the one currently installed

**Comment by PeterStrick** [comment]
> @PeterStrick actually, this doesn't work very well: the setting selects the latest build (which is the Canary one, with the highest build number), but not the one currently installed

I'll add an option to load the current one if Available
