### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by jakeyounglol** [PeterStrick/ViVeTool-GUI#61]
i have an arm64 based mac and i'm using a virtual machine to run windows and i can't use vivetool gui because it doesn't support arm based computers. please add arm64 support. vivetool cli supports arm64 too.

**Comment by PeterStrick** [comment]
Hmmm Debugging Arm64 Builds of ViVeTool GUI would be a challenge because I don't own a Arm64 Device capable of running Windows, but I'll try to get a Arm64 Build working later today

**Comment by PeterStrick** [comment]
Well this seems to be kind of difficult to get working correctly. After applying the fix mentioned here https://github.com/dotnet/sdk/issues/28419 it does indeed compile Arm64 Versions of ViVeTool GUI, the Feature Scanner and a WebView2 DLL, although all other DLLs, including Mach2 seem to be x86-64 only so it seems that you are required to rely on a x64 to Arm64 Translation Layer

Compiling for Arm64 also seems to introduce a Bug where it is not compiling any Localised Resources, removing any Multi-Language Support

![image](https://github.com/PeterStrick/ViVeTool-GUI/assets/60312421/e6b232d3-c01d-47f2-bf30-9722dfb04c2a)

The ARM64 compiled Version is here: [ViVeTool_GUI_ARM64.zip](https://github.com/PeterStrick/ViVeTool-GUI/files/11475523/ViVeTool_GUI_ARM64.zip)

**Comment by jakeyounglol** [comment]
ok thanks!
