### ISSUE TITLE
[Bug] New versions of Windows 11 Home not detected by ViVeTool-GUI

### ISSUE THREAD

**Issue by MasterMarius** [PeterStrick/ViVeTool-GUI#63]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ViVeTool_GUI.GUI.LoadFromManualTXT() in F:\Development\Visual Studio Projects\ViVeTool-GUI\vivetool-gui\GUI.vb:line 472
![image_2023-06-09_210659517](https://github.com/PeterStrick/ViVeTool-GUI/assets/113457838/aa2521e5-b2e2-4b42-b319-f846e12511c6)

 - Windows Build: 22621.1778
 - ViVeTool-GUI Version: ViVeTool.GUI.1.6.2.0.Portable

**Comment by MasterMarius** [comment]
"Edition	Windows 11 Home
Version	22H2
Installed on	‎23.‎05.‎2023
OS build	22621.1778
Experience	Windows Feature Experience Pack 1000.22642.1000.0
"

**Comment by PeterStrick** [comment]
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
at ViVeTool_GUI.GUI.LoadFromManualTXT() in F:\Development\Visual Studio Projects\ViVeTool-GUI\vivetool-gui\GUI.vb:line 472

That Error only appears if you try to load a downloaded Feature List Text File that is malformed, or not a Feature List at all.

At the Build Drop Down Combo-box, select a Bild that is closest to your Installed Build

**Comment by MasterMarius** [comment]
The id for combined directories in taskbar is not presesnt as an ID in build 22621. eg I'm looking for [id](id:29785186) that for my build isn't activated/disponible

**Comment by PeterStrick** [comment]
You can press on The "Manually change a Feature" Button, enter the ID and Enable it

**Comment by MasterMarius** [comment]
yes but I don't have a visual of my activated id's if I use this method, I think

**Comment by MasterMarius** [comment]
It not changed a thing

**Comment by PeterStrick** [comment]
Ah sorry, that ViVeTool Feature only exists in Windows 11 Dev Build **23466**. You have Build **22621**

This has nothing to do with Home/Pro Editions

**Comment by MasterMarius** [comment]
so What's the solution?

**Comment by PeterStrick** [comment]
> so What's the solution?

Upgrade from to the latest Windows 11 Dev Insider Preview Build, by registering as a Windows Insider. Be aware though, that experimental and development Builds of Windows are prone to be unstable/buggy

**Comment by MasterMarius** [comment]
can't join to the inside team, stuck at viewing the Program Agreement and Privacy Statement. Continue button is grayed

**Comment by PeterStrick** [comment]
Try the following Article to become a Windows Insider https://support.microsoft.com/en-us/windows/join-the-windows-insider-program-and-manage-insider-settings-ef20bb3d-40f4-20cc-ba3c-a72c844b563c

Other than that I can't really help you
