### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by raginhard76** [PeterStrick/ViVeTool-GUI#64]
**Describe the bug**
At launch :

System.ArgumentOutOfRangeException: L'index était hors limites. Il ne doit pas être négatif et doit être inférieur à la taille de la collection.
Nom du paramètre : index
   à System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   à System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   à ViVeTool_GUI.GUI.PopulateBuildComboBox() dans F:\Development\Visual Studio Projects\ViVeTool-GUI\vivetool-gui\GUI.vb:ligne 302

**Screenshots**
![image](https://github.com/PeterStrick/ViVeTool-GUI/assets/82544232/b4dfd4b9-c9c7-4437-b99c-ed311e6e8e6b)

**Desktop (please complete the following information):**
 - Windows Build: 23493
 - ViVeTool-GUI Version: 1.6.2

**Comment by PeterStrick** [comment]
That seems to be a Bug in the 1.6.x Version of ViVeTool GUI

Recent testing of Version 1.7 shows no Issues for Automatically loading a Feature List

I'll try to finish testing ViVeTool GUI v1.7 so that I can release it

**Comment by PeterStrick** [comment]
You can try to test it on the latest 1.7 Version of ViVeTool GUI, or create a new Bug Report when 1.7 releases, if the Issue still occurs

**Comment by raginhard76** [comment]
how download 1.7 ? i only see feature scanner :/

**Comment by PeterStrick** [comment]
> how download 1.7 ? i only see feature scanner :/

I'll compile it for you one moment

**Comment by PeterStrick** [comment]
@raginhard76 Due to recent changes in the mach2 Repo, the current Version in the v1.7-Testing Branch has been released to the Public as an Emergency Hotfix. Simply restart ViVeTool-GUI and update to 1.6.999.3

**Comment by raginhard76** [comment]
Update : okay
no code error, but stay like this : 
![image](https://github.com/PeterStrick/ViVeTool-GUI/assets/82544232/f21823e4-b7d2-4dce-9cde-825aedf07030)

**Comment by PeterStrick** [comment]
> Update : okay
> no code error, but stay like this : 
> ![image](https://github.com/PeterStrick/ViVeTool-GUI/assets/82544232/f21823e4-b7d2-4dce-9cde-825aedf07030)
> 

You may need to wait a few Minutes while it is loading, indicated by the Status Text at the Bottom Left
