### ISSUE TITLE
[Bug] - Build 1.7 rev2 (17.07.2023) - GUI translation issues

### ISSUE THREAD

**Issue by bovirus** [PeterStrick/ViVeTool-GUI#67]
**Describe the bug**

GUI translation issues

**To Reproduce**

Check screenshot

**Expected behavior**

Fix translation issues

**Screenshots**

![image](https://github.com/PeterStrick/ViVeTool-GUI/assets/1262554/b6ff6308-1eef-4bab-8d97-afd9aebcdd8c)
Red boxes - Strings untranslated

![image](https://github.com/PeterStrick/ViVeTool-GUI/assets/1262554/6d324a01-8e94-4623-a507-e37a660ac7e9)
Red boxes - Strings untranslated

![image](https://github.com/PeterStrick/ViVeTool-GUI/assets/1262554/ebb3bfae-8465-4a3b-be88-cbb2d60c1b8a)
Same text string for window caption and text description.
Please use two different strings.

![image](https://github.com/PeterStrick/ViVeTool-GUI/assets/1262554/076bd8ce-5856-4510-8daa-4848dc8c19d3)
In language selection is not showed the current language selected.

![image](https://github.com/PeterStrick/ViVeTool-GUI/assets/1262554/2c76ac30-3bab-4c48-845b-cbe4b8ed5a2e)
Red boxes - Strings untranslated

![image](https://github.com/PeterStrick/ViVeTool-GUI/assets/1262554/c3e51885-63e9-4ea4-93a6-9b51d5fc6527)
If you select "Function state" the string for column head is croppd.
decrese column width for "Function Name", laave as it is for "Funection ID" and increase for "Function State".
 

**Desktop (please complete the following information):**
 - Windows Build: Windows 11 22H2 64bit italian 
 - ViVeTool-GUI Version: 17.07.203

**Comment by bovirus** [comment]
@PeterStrick 

https://weblate.rawrr.dev/projects/vivetool-gui/vivetool-gui-v17-testing-aboutandsettings/it/

Translated some strings
Remain 34 strings that seems not need translation
Please check failed checks and incoerency (wrong info).

**Comment by PeterStrick** [comment]
> @PeterStrick
> 
> https://weblate.rawrr.dev/projects/vivetool-gui/vivetool-gui-v17-testing-aboutandsettings/it/
> 
> Translated some strings Remain 34 strings that seems not need translation Please check failed checks and incoerency (wrong info).

I edited the Bulk Edit add-on to not add the read-only flag to any string that ends with .Text. This shold hopefully resolve the read-only Problems

- The String in Picture 1 is translated
- The Strings in Picture 2 and 5 still need translation: https://weblate.rawrr.dev/translate/vivetool-gui/vivetool-gui-v17-testing-setmanual/it/?q=state%3Aempty&offset=1
- The Text in Picture 3 has been changed
- The Text in Picture 4 now shows your current Langage
- I added more spacing to the Columns in Picture 6

**Comment by bovirus** [comment]
@PeterStrick 

Italian translation completed.
