### ISSUE TITLE
Add support for big screens with hidpi

### ISSUE THREAD

**Issue by uom42** [PeterStrick/ViVeTool-GUI#75]
It's so weird in late 2023 to have a fixed size window containing variable size data (tables, lists, etc.) it looks like something out of the late 90's!
Please let's add support for variable size main window and support for hidpi displays so that system UI scaling happens correctly!

**Describe the solution you'd like**
Please add:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	...
	<System.Windows.Forms.ApplicationConfigurationSection>
		<add key="DpiAwareness" value="PerMonitorV2" />
	</System.Windows.Forms.ApplicationConfigurationSection>
	... 
</configuration>
```
into App.config

And please change:
```
Private Sub InitializeComponent()
		...
		Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable
		Me.MaximizeBox = True
		Me.MinimumSize = New Drawing.Size(600, 400)
		...
End Sub

```
in GUI.Designer.vb

**Comment by uom42** [comment]
And maybe we can add:
```
Private Sub InitializeComponent()
		...
		Me.StartPosition = FormStartPosition.CenterParent
		...
End Sub
```
into vivetool-gui\AboutAndSettings.Designer.vb

**Comment by PeterStrick** [comment]
I don't own a HiDPI Monitor personally so have never tested my Applications against them, could you try downloading the [Build Artifact](https://github.com/PeterStrick/ViVeTool-GUI/actions/runs/6847368815) and see if it supports HiDPI Monitors as intended now?

ViVeTool GUI and the Feature Scanner have been changed accordingly, and also made Sizeable

**Comment by uom42** [comment]
My friend, everything works perfectly! 
You are the best!
