### ISSUE TITLE
Feature button that detects version and windows and what we can enable via Viva Tools

### ISSUE THREAD

**Issue by ilijamilcinoski** [PeterStrick/ViVeTool-GUI#76]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
To have a button that detects the version of windows and to have better option what can be enabled in Viva tools

**Describe alternatives you've considered**
I have not considered any 
**Additional context**
The dropdown menu where we select all the versions of Windows

**Comment by PeterStrick** [comment]
A button to just magically tell you what ViVeTool Features you can enable or not is impossible. 

Generally, you can Enable and Disable any Feature that you see within the Feature List for your Version and Build of Windows.

What these Features do, if they take effect and if they need additional changes to work is unknown, outside of People that try them out for themselves and post their findings on the Internet.

There is a Setting within ViVeTool 1.7 that allows you to automatically load the latest Feature List for your Version of Windows, if available. From there out you sort of venture into the land of unknown trying out Features

**Comment by PeterStrick** [comment]
Closing due to no response
