### ISSUE TITLE
Ability to opt out of beta releases

### ISSUE THREAD

**Issue by zwresn453** [PeterStrick/ViVeTool-GUI#77]
**Is your feature request related to a problem? Please describe.**
The automatic updater does not mention that a suggested update is actually a beta release.

**Describe the solution you'd like**
A setting that stops the automatic updater from suggesting beta releases

**Describe alternatives you've considered**
Never update the program

**Additional context**

**Comment by PeterStrick** [comment]
The Auto Updater suggests that Beta Release due to it needing to be pushed out to all Users due to the Stable 1.6.2 Release not functioning anymore due to Changes in the mach2 Repository

**Comment by PeterStrick** [comment]
Closing due to no response
