### ISSUE TITLE
Latest windows update changed feature Id's

### ISSUE THREAD

**Issue by azza19861** [PeterStrick/ViVeTool-GUI#85]
With the latest update of Windows 11 23H2 build 22631.3593 (kb5037771). We used to disable ID's 40950262,41076133 which reverted the file explorer to the classic version with the ribbon. After this update the above ID's don't work.

**Comment by PeterStrick** [comment]
> With the latest update of Windows 11 23H2 build 22631.3593 (kb5037771). We used to disable ID's 40950262,41076133 which reverted the file explorer to the classic version with the ribbon. After this update the above ID's don't work.

While there is no Feature List for Build 22631.x, later Windows 11 Insider Dev/Canary Builds have seemingly moved the IDs **40950262** and **41076133** from **Modifiable/Unknown** to **Always Enabled**, making it effectively unable to be modified by either ViVeTool GUI or ViVeTool itself, which I suspect is the case for 22631.3593.
