### ISSUE TITLE
[Bug] features file is not being created after mach2 scan

### ISSUE THREAD

**Issue by Bluscream** [PeterStrick/ViVeTool-GUI#86]
**Describe the bug**
features file is not being created after mach2 scan

**To Reproduce**
1. Go through the feature scanner wizard until the "Done" tab is active
2. Try the "Save the Features.txt File" button
3. Get the error from the screenshot below

**Expected behavior**
duh

**Screenshots**
![image](https://github.com/PeterStrick/ViVeTool-GUI/assets/3318223/528cea26-a34a-4da5-b842-6e639f170af0)

**Desktop (please complete the following information):**
 - Windows Build: 10.0.22631.3737
 - ViVeTool-GUI Version: 172

**Comment by PeterStrick** [comment]
This should be fixed in the upcoming Version 1.7 Release, although due to limited Time because of School, Work, Friends and attending to my Boyfriend, progress on developing ViVeTool GUI got slow and delayed, I apologize
