### ISSUE TITLE
DisableWin10Taskbar not working

### ISSUE THREAD

**Issue by TheKidRock** [PeterStrick/ViVeTool-GUI#88]
**Describe the bug**
On Windows 24H2, the feature id "42537950" - DisableWin10Taskbar is not working. 

**To Reproduce**
Disable the id "DisableWin10Taskbar, 42537950"

**Expected behavior**
Should have activated Win10 Taskbar but it did not work.

**Desktop (please complete the following information):**
 - Windows Build: Windows 11 24H2
 - ViVeTool-GUI Version: ViVeTool GUI v1.7 Pre-Release 2

**Comment by PeterStrick** [comment]
As far as I can tell by looking at [NeoWin](https://www.neowin.net/news/windows-11-build-26002-adds-a-feature-id-that-breaks-the-old-windows-10-taskbar/) Disabling the ID 42537950 does not bring back the Windows 10 Taskbar, but allows you to use 3rd Party Programs like [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher/issues/3398) to do so.

Enabling the ID, which seems what Microsoft is trying to do in the future but permanently, breaks Programs like ExplorerPatcher and StartAllBack from using the Windows 10 Taskbar at all.

**Comment by Anixx** [comment]
Explorer Partcher removed the feature to enable Win10 taskbar from builds 26000+. You needto use an older version of Eexplorer Patcher.
